### ISSUE TITLE
AF SDK version compatibility

### ISSUE THREAD

**Issue by jdryden-osi** [osisoft/PI-Security-Audit-Tools#298]
Changes to AF SDK object structures have been seen to affect the functionality of the audit checks. One example is that with AF SDK 2.8, the check for a good AF Server connection below will fail:

```
$global:AFServerConnection = Connect-AFServer -AFServer $(Get-AFServer -Name $ComputerParams.ComputerName)
if($global:AFServerConnection.ConnectionInfo.IsConnected)
```

In AF SDK 2.8 the IsConnected property is accessed directly on the connection object, like below:

`$global:AFServerConnection.IsConnected`

There are likely other instances of such incompatibilities. Tests should be run with at least the more recent AF SDK versions.

**Comment by hpaul-osi** [comment]
Further investigation revealed that this behavior is actually due to do with PowerShell tools releases prior to 2.x using custom PSObjects instead of AFSDK objects. Though this discrepancy in IsConnected was handled in #302 there are likely other behavioral differences with the 1.x PowerShell Tools for the PI System.  

When checking for OSIsoft.PowerShell, we should also verify the major version is at least 2 and return a warning to upgrade to latest PI SMT for best performance.
